runtime: nodejs18
service: default
handlers:
  # Optional: Add specific API routes handled *by Node.js* if any
  # - url: /api/some-frontend-api/.*
  #   script: auto
  #   secure: always
  - url: /(.*\..+)$ # Static assets
    static_files: build/\1
    upload: build/(.*\..+)$
    secure: always
  - url: /.* # SPA fallback
    static_files: build/index.html
    upload: build/index.html
    secure: always
