runtime: nodejs18
service: frontend

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
    secure: always

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always