runtime: nodejs22
service: default
handlers:
  # Optional: If your Node.js app has its own API handlers needed by the frontend itself
  # - url: /api/some-frontend-api/.*
  #   script: auto
  #   secure: always
  - url: /(.*\..+)$ # Static assets (CSS, JS, images)
    static_files: build/\1
    upload: build/(.*\..+)$
    secure: always
  - url: /.* # Catch-all for SPA routing
    static_files: build/index.html
    upload: build/index.html
    secure: always
