runtime: python39 # Or your chosen Python version
service: backend
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  # IMPORTANT: Replace placeholders below with actual values locally before deploying,
  # OR configure and use Secret Manager (preferred). Do not commit secrets!
  WEBRISK_API_KEY: TBD
  GOOGLE_CLOUD_PROJECT_NUMBER: TBD

health_check:
  enable_health_check: True

inbound_services:
  - warmup
